"""updated some tables

Revision ID: 008b0e6cdc10
Revises: 2b98027cabf4
Create Date: 2023-08-27 08:56:58.496485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008b0e6cdc10'
down_revision = '2b98027cabf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
