"""added user_id and user fields to the profile table

Revision ID: 065e9a4d1a75
Revises: 3392dca4aef4
Create Date: 2023-08-02 17:27:54.344571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065e9a4d1a75'
down_revision = '3392dca4aef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
