"""modified the structure of the models a bit

Revision ID: 150ec8964d16
Revises: fa6f04f7d65c
Create Date: 2023-08-19 10:00:55.915535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150ec8964d16'
down_revision = 'fa6f04f7d65c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
