"""added the description column in the programs table

Revision ID: 1815b9d305f3
Revises: e881a62b160e
Create Date: 2023-08-07 11:46:11.364269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1815b9d305f3'
down_revision = 'e881a62b160e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('description', sa.String(length=300), server_default='No description', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'description')
    # ### end Alembic commands ###
