"""added columns to the recipes table

Revision ID: 1c155e3c717a
Revises: 841172fa1491
Create Date: 2023-08-25 17:44:32.858293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c155e3c717a'
down_revision = '841172fa1491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('total_calories', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('total_proteins', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('total_carbs', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('total_fats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'total_fats')
    op.drop_column('recipes', 'total_carbs')
    op.drop_column('recipes', 'total_proteins')
    op.drop_column('recipes', 'total_calories')
    # ### end Alembic commands ###
