"""deleted the user_id and user columns from the unit table

Revision ID: 1fe2c255ace2
Revises: 065e9a4d1a75
Create Date: 2023-08-04 09:55:45.588289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe2c255ace2'
down_revision = '065e9a4d1a75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('units_user_id_fkey', 'units', type_='foreignkey')
    op.drop_column('units', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('units_user_id_fkey', 'units', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
