"""changed the string to DATE

Revision ID: 2b98027cabf4
Revises: 498407690b1a
Create Date: 2023-08-26 19:14:04.260878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b98027cabf4'
down_revision = '498407690b1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
