"""deleted the relationship in the workout_exercises table

Revision ID: 2d0107f922d5
Revises: bfddb2eaf5ef
Create Date: 2023-08-11 13:48:22.138969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0107f922d5'
down_revision = 'bfddb2eaf5ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_exercises_unit_id_fkey', 'workout_exercises', type_='foreignkey')
    op.drop_column('workout_exercises', 'unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('workout_exercises_unit_id_fkey', 'workout_exercises', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###
