"""added the ingredients column to the recipes table

Revision ID: 36aea94b3eb9
Revises: cfe5b93bacbd
Create Date: 2023-08-25 17:29:01.189398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36aea94b3eb9'
down_revision = 'cfe5b93bacbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###
