"""updated some tables

Revision ID: 3bf9b0a267dc
Revises: 008b0e6cdc10
Create Date: 2023-08-27 09:22:03.544065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf9b0a267dc'
down_revision = '008b0e6cdc10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
