"""added the unit field to the unit model

Revision ID: 3c303715e4e9
Revises: 5e59c72f1c2e
Create Date: 2023-08-01 18:53:51.635645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c303715e4e9'
down_revision = '5e59c72f1c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('unit', sa.String(length=100), server_default='Kg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'unit')
    # ### end Alembic commands ###
