"""modified the profile_picture column

Revision ID: 418b924d86e3
Revises: ad7c445668df
Create Date: 2023-08-26 13:34:19.200929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418b924d86e3'
down_revision = 'ad7c445668df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
