"""changed the string to DATE

Revision ID: 498407690b1a
Revises: 418b924d86e3
Create Date: 2023-08-26 19:09:36.836198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498407690b1a'
down_revision = '418b924d86e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
