"""altered the date fields

Revision ID: 5ebc665a8391
Revises: 60f4631708f6
Create Date: 2023-08-04 18:25:05.916309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebc665a8391'
down_revision = '60f4631708f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
