"""added created_at fields and date field in the bodyweight table

Revision ID: 60f4631708f6
Revises: fdec96d664f0
Create Date: 2023-08-04 17:51:58.042169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f4631708f6'
down_revision = 'fdec96d664f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_weight_units', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('body_weights', sa.Column('date', sa.String(length=100), server_default='2023-08-04 17:51:56.796582', nullable=False))
    op.add_column('body_weights', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_weights', 'created_at')
    op.drop_column('body_weights', 'date')
    op.drop_column('body_weight_units', 'created_at')
    # ### end Alembic commands ###
