"""added user_id field to the workout_exercise_sets table

Revision ID: 6d0c1ecbd723
Revises: 864d0877ea48
Create Date: 2023-08-08 10:35:04.655254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0c1ecbd723'
down_revision = '864d0877ea48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercise_sets', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercise_sets', 'user_id')
    # ### end Alembic commands ###
