"""modified the date back to a string

Revision ID: 81a546f90aca
Revises: 3bf9b0a267dc
Create Date: 2023-08-27 10:24:11.372328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a546f90aca'
down_revision = '3bf9b0a267dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
