"""added the ingredients column to the recipes table

Revision ID: 841172fa1491
Revises: 36aea94b3eb9
Create Date: 2023-08-25 17:30:01.825023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841172fa1491'
down_revision = '36aea94b3eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
