"""deleted some fields in the workout_exercises table

Revision ID: 864d0877ea48
Revises: eea1bbb668dc
Create Date: 2023-08-08 09:52:24.823700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864d0877ea48'
down_revision = 'eea1bbb668dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercises', 'reps')
    op.drop_column('workout_exercises', 'unit')
    op.drop_column('workout_exercises', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('weight', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('workout_exercises', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('workout_exercises', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
