"""added back the user id field

Revision ID: 9c9e266ad9fd
Revises: 1fe2c255ace2
Create Date: 2023-08-04 10:02:28.433845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9e266ad9fd'
down_revision = '1fe2c255ace2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'units', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_column('units', 'user_id')
    # ### end Alembic commands ###
