"""changed the datatypes for the food info

Revision ID: 9cf5aa27a548
Revises: 1c155e3c717a
Create Date: 2023-08-26 09:06:23.969356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf5aa27a548'
down_revision = '1c155e3c717a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
