"""added user_id column to the workout_exercises table

Revision ID: a6ba5f2bed30
Revises: 150ec8964d16
Create Date: 2023-08-19 13:24:54.788360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ba5f2bed30'
down_revision = '150ec8964d16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercises', 'user_id')
    # ### end Alembic commands ###
