"""initial commit with 2.0 styled sqlalchemy models

Revision ID: a7b7ffd16a24
Revises: d37ab4b66f93
Create Date: 2023-08-16 18:28:58.422940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b7ffd16a24'
down_revision = 'd37ab4b66f93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
