"""created the favorite_foods and recipes tables

Revision ID: c0f748e11f43
Revises: fa6b9c20a1b9
Create Date: 2023-08-25 17:19:37.082145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f748e11f43'
down_revision = 'fa6b9c20a1b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
