"""added date field to Workout Model

Revision ID: cf493cbb9aa9
Revises: 5e0592411b8f
Create Date: 2023-07-31 17:51:01.588297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf493cbb9aa9"
down_revision = "5e0592411b8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts", sa.Column("date", sa.String(), nullable=False, server_default="now")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "date")
    # ### end Alembic commands ###
