"""created the favorite_foods and recipes tables

Revision ID: cfe5b93bacbd
Revises: c0f748e11f43
Create Date: 2023-08-25 17:22:03.136064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe5b93bacbd'
down_revision = 'c0f748e11f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_foods',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calories_per_100g', sa.Integer(), nullable=False),
    sa.Column('proteins_per_100g', sa.Integer(), nullable=False),
    sa.Column('carbs_per_100g', sa.Integer(), nullable=False),
    sa.Column('fats_per_100g', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('favorite_food_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_food_id'], ['favorite_foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('favorite_foods')
    # ### end Alembic commands ###
