"""deleted the backpopulates in the workouts table

Revision ID: d37ab4b66f93
Revises: 25078cd339d2
Create Date: 2023-08-15 17:51:56.193854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37ab4b66f93'
down_revision = '25078cd339d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
