"""replaced the url by picture_id

Revision ID: dedff5e53293
Revises: 81a546f90aca
Create Date: 2023-08-27 14:30:00.373982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedff5e53293'
down_revision = '81a546f90aca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_pictures', sa.Column('picture_id', sa.TEXT(), nullable=False))
    op.drop_column('profile_pictures', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_pictures', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('profile_pictures', 'picture_id')
    # ### end Alembic commands ###
