"""modified the programs table

Revision ID: e0b16c14be88
Revises: 63b5e47e8524
Create Date: 2023-08-07 13:11:38.143706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b16c14be88'
down_revision = '63b5e47e8524'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('n_days', sa.Integer(), server_default='7', nullable=False))
    op.alter_column('programs', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'New program'::character varying"))
    op.alter_column('programs', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False,
               existing_server_default=sa.text("'No description'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programs', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True,
               existing_server_default=sa.text("'No description'::character varying"))
    op.alter_column('programs', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'New program'::character varying"))
    op.drop_column('programs', 'n_days')
    # ### end Alembic commands ###
