"""created the workout_sets table

Revision ID: e5c0a73bebb2
Revises: e0b16c14be88
Create Date: 2023-08-08 09:27:17.590666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c0a73bebb2'
down_revision = 'e0b16c14be88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(precision=1), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workout_exercises', sa.Column('n_sets', sa.Integer(), nullable=False))
    op.drop_column('workout_exercises', 'sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('workout_exercises', 'n_sets')
    op.drop_table('workout_sets')
    # ### end Alembic commands ###
