"""altered the date fields

Revision ID: e881a62b160e
Revises: 5ebc665a8391
Create Date: 2023-08-04 18:34:07.866397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e881a62b160e'
down_revision = '5ebc665a8391'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
