"""change the relationship name of workout_exercises table

Revision ID: eea1bbb668dc
Revises: 4424390907fd
Create Date: 2023-08-08 09:49:29.237765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea1bbb668dc'
down_revision = '4424390907fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
