"""added day, month and year columns to the workouts table

Revision ID: f72495f5ee87
Revises: a6ba5f2bed30
Create Date: 2023-08-20 11:42:02.145614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72495f5ee87'
down_revision = 'a6ba5f2bed30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('day', sa.Integer(), nullable=False))
    op.add_column('workouts', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('workouts', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'year')
    op.drop_column('workouts', 'month')
    op.drop_column('workouts', 'day')
    # ### end Alembic commands ###
