"""added the bodyweight column to the profiles table

Revision ID: fa6b9c20a1b9
Revises: f72495f5ee87
Create Date: 2023-08-25 15:55:19.248206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6b9c20a1b9'
down_revision = 'f72495f5ee87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bodyweight', sa.Float(precision=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'bodyweight')
    # ### end Alembic commands ###
