"""added bodyweight and bodyweight unit tables

Revision ID: fdec96d664f0
Revises: 9c9e266ad9fd
Create Date: 2023-08-04 17:47:20.248641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdec96d664f0'
down_revision = '9c9e266ad9fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_weight_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=100), server_default='Kg', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(precision=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('body_weights')
    op.drop_table('body_weight_units')
    # ### end Alembic commands ###
